nextmcloud/ios

- iOSClient/Extensions/UIAlertController+Extension.swift
NMC 1182 Create Folder (while moving a file) - there might be a longer waiting time without loading spinner
> NMC 1182 - Added a loading spinner after creating a file and saved

- iOSClient/Select/NCSelectCommandViewSelect+CreateFolder.xib
Settings / Auto-Upload - Button title "Ordner erstellen" reduced to "Orde...stellen
> NMC 1180 - create folder button size update

- iOSClient/Settings/CCManageAutoUpload.m
Auto Upload: No prompt to delete uploaded files from the gallery even though the option is turned on
> NMC 1207 - Option removed as not present in nextcloud app

- iOSClient/Main/Create cloud/NCCreateFormUploadAssets.swift
Files - Switches are reset after rotating the device
> NMC 990 - Check added for switch status

- iOSClient/Settings/NCSettings.m
NMC - 1414- Removed "Experimental" text from title E2E.
> NMC- 1414- Removed "experimental" text.

- iOSClient/Main/Create cloud/NCCreateFormUploadDocuments.swift
- iOSClient/Menu/AppDelegate+Menu.swift
create office CR file without entering the name default text file get created
> NMC 1419 - extension added for default file name

- iOSClient/Supporting Files/de.lproj/Localizable.strings
German string updated for uploading e2e encryption file
> NMC 1447 - German string updated for uploading e2e encryption file

- iOSClient/Main/NCFunctionCenter.swift
disable sharing for encrypted folders
> NMC 1443 - disable sharing for encrypted folders

- iOSClient/Share/NCShare.swift
- iOSClient/Share/NCShareAdvancePermission.swift
Edit Condition update for collabora files
> NMC 1385 - Edit Condition update for collabora files

- iOSClient/Main/Create cloud/NCCreateFormUploadDocuments.swift
- iOSClient/Supporting Files/de.lproj/Localizable.strings
- iOSClient/Supporting Files/en.lproj/Localizable.strings
empty check added for file name
> NMC 1428 - empty check added for file name

- iOSClient/Rename file/NCRenameFile.storyboard
- iOSClient/Rename file/NCRenameFile.swift
Rename alert theme color change
> NMC 1415 - Rename alert theme color change

- iOSClient/Main/NCFunctionCenter.swift
NMC - 1592 -  renaming of encrypted folder shows error
> NMC - 1592 - Rename and copy/move option removed for encrypted folder

- iOSClient/Main/NCFunctionCenter.swift
- iOSClient/Menu/NCCollectionViewCommon+Menu.swift
- iOSClient/Menu/NCViewer+Menu.swift
Favourite option removed for encrypted media
> NMC 1606 - Favourite option removed for encrypted media

- iOSClient/Main/Create cloud/NCCreateFormUploadScanDocument.swift
NMC - 1605 -  Image file shows blank in after saved scans
> NMC - 1605 - Fixed image and file preview/display for scan documents.

- iOSClient/Main/Create cloud/NCCreateFormUploadScanDocument.swift
Scan image save multiple images
> NMC 1605 - Scan document multiple image upload

- iOSClient/Main/NCFunctionCenter.swift
- iOSClient/Menu/NCCollectionViewCommon+Menu.swift
NMC - 1624 - iOS Encrypted folder should not contain delete option
> NMC - 1624 - Removed delete option for encrypted folder

- iOSClient/Viewer/NCViewer.swift
Encrypted Folder - Office documents are not opened due to error
> NMC 1637 - Check added for encrypted folder

- iOSClient/Main/Collection Common/NCCollectionViewCommon.swift
NMC - 1636 -  Files - Applying different sorting options in grid view hide all files except folders.
> NMC - 1636 - Sorting option fixed for grid view

- iOSClient/Data/NCDatabase.swift
- iOSClient/Settings/CCManageAutoUpload.m
Remove from camera roll option added in auto upload screen
> NMC 1683 - Remove from camera roll option added in auto upload screen

- iOSClient/Main/Create cloud/NCCreateFormUploadAssets.swift
NMC 1620 - iOS - LivePhoto upload in encrypted folder leads to data garbage
> NMC 1620 - Live photo upload creates garbage data fixes

- iOSClient/Data/NCDatabase.swift
- iOSClient/Settings/CCManageAutoUpload.m
delete alert shown after auto upload complete
> NMC 1683 - value update in local db

- iOSClient/Main/Collection Common/NCCollectionViewCommon.swift
NMC 1691 - Add folder info is not showing on header.
> NMC 1691 Add folder info showing on saved and can edit the info

- iOSClient/Data/NCManageDatabse+Metadata.swift
- iOSClient/Networking/NCNetworking.swift
- iOSClient/Supporting Files/de.lproj/Localizable.strings
- iOSClient/Supporting Files/en.lproj/Localizable.strings
Sharing - Wrong sharing-status after editing file shared by another user
> NMC 955 - Alert added for save overwrite file

- iOSClient/AudioRecorder/NCAudioRecorderViewController.swift
NMC 1630 -  Files: The app crashes when stopping audio recording
> NMC 1630 - Fixed issue for audio recording

- iOSClient/Menu/AppDelegate+Menu.swift
NMC 1709 - E2E - folder creation inside encrypted folder
> NMC 1709 - Inside encrypted folder option changed to "create folder"

- iOSClient/Share/NCShare.storyboard
NMC 663 - Sharing- Landscape mode input text field getting overlap by keyboard.
> NMC 663 - Changes on the (NCShare) Storyboard

- iOSClient/Main/NCFunctionCenter.swift
- iOSClient/Menu/NCCollectionViewCommon+Menu.swift
E2EE: Subfolder encrypted have rename option
> NMC 1711 - Rename option removed from encrypted folder

- iOSClient/Recent/NCRecent.swift
"recent files" - sharing for encrypted files is available
> NMC 1511 - Update condition as per encryption

- iOSClient/Recent/NCRecent.swift
Inside folders removed from root in recent files
> NMC 1511 - Inside folders removed from root in recent files

- iOSClient/Share/NCShare.swift
NMC 663 - Sharing- Search box getting overlap with search results
> NMC 663 - Changed the height for textfiled overlapping keyboard

- iOSClient/Data/NCDataSource.swift
- iOSClient/Menu/NCCollectionViewCommon+Menu.swift
set file offline not shown for newly created file
> Nmc 1186 set file offline not shown for newly created file

- iOSClient/AppDelegate.swift
- iOSClient/Data/NCManageDatabase.swift
- iOSClient/Networking/NCNetworking.swift
- iOSClient/Networking/NCNetworkingE2EE.swift
upload to encrypted folder leads to "file locked" error message (loop!)
> NMC 1618 - Unlock encrypted folder 

- iOSClient/Share/NCShare.swift
NMC 1751 - Sharing - App crashes while switching into landscape mode
> NMC 1751 - Landscape mode fix for share option

- iOSClient/Supporting Files/de.lproj/Localizable.strings
- iOSClient/Supporting Files/en.lproj/Localizable.strings
- iOSClient/Utility/NCUtility.swift
- iOSClient/Viewer/NCViewerMedia/NCPlayer/NCPlayer.swift
Videos in E2E folder get broken after deleting from cache
> NMC 1745 Videos in E2E folder get broken after deleting from cache

- iOSClient/Share/NCShare.swift
> NMC 1385 - Quick action update

- iOSClient/BrowserWeb/NCBrowserWeb.swift
- iOSClient/Viewer/NCViewerNextcloudText/NCViewerNextcloudText.swift
- iOSClient/Viewer/NCViewerRichdocument/NCViewerRichdocument.swift
- Office Suite - Endless loading after cancelling the print
- Preview button leads to app selector screen with a filename without suffix. in the background a loading spinner is shown
> Nmc 1727 preview button leads to app selector screen

- iOSClient/Main/Collection Common/NCCollectionViewCommon.swift
NMC - 1749 -  Search - Files location are shown in favourite section when user is in search.
> NMC - 1749 - Searching mode disabled while switching tabs

- iOSClient/Main/NCFunctionCenter.swift
Files - Nothing happened when tapping on "Ausdrucken" (Print)
> NMC 1748 - Files - Nothing happened when tapping on "Ausdrucken" (Print)

- iOSClient/Menu/NCCollectionViewCommon+Menu.swift
- iOSClient/Menu/NCMenuAction.swift
Print option enabled on three dots menu
> NMC 1748 - Print option enabled on three dots menu

- iOSClient/Main/Collection Common/NCCollectionViewCommon.swift
- iOSClient/NCGlobal.swift
- iOSClient/Select/NCSelect.swift
Notification added after copy move view dismiss
> NMC 1746 - Move or copy files - Folder views is broken when changing the view and sorting in Copy/Move layer

- iOSClient/Viewer/NCViewerQuickLook/NCViewerQuickLook.swift
NMC 2356 - After image rotation, file size got increases
> NMC 2356 - Changed compression quality of UIImage

- iOSClient/Viewer/NCViewerMedia/NCViewerMediaDetailView.swift
NMC 2396 - Media Gallery - Date not available is shown for all images (although images are sorted by date)
> NMC - 2396 - Date not available issue fix

- iOSClient/Data/NCManageDatabase+Metadata.swift
- iOSClient/Main/NCPickerViewController.swift
- Fixes multiple files not uploading
- Also fixes conflict window, where before it would only show 1 conflict and ignore the rest. Now it shows multiple conflicts (if any), and processes all of them, while files that don't have a conflict continue being uploaded normally.
> NMC 2403 - Files - Only one file is uploaded
